# Generated by Django 2.1.1 on 2018-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('isLive', models.BooleanField(default=False)),
                ('publication_date', models.DateField(auto_now=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
