# Generated by Django 2.1.1 on 2018-11-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('isLive', models.BooleanField(default=False)),
                ('publication_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
