# Generated by Django 2.1.1 on 2018-11-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_page_isinvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='isTitleVisable',
            field=models.BooleanField(default=False),
        ),
    ]
