# Generated by Django 2.1.1 on 2018-11-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_page_istitlevisable'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tagline',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
